apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
        - name: simple-webapp
          image: htyagi2233/simple-webapp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local   # preserve client IP
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 8080

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: simple-webapp
# spec:
#   type: NodePort
#   selector:
#     app: simple-webapp
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 31180

